# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  finger_joint:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  joint_a1:
    has_velocity_limits: true
    max_velocity: 1.83259571459
    has_acceleration_limits: false
    max_acceleration: 0
  joint_a2:
    has_velocity_limits: true
    max_velocity: 1.86750229963
    has_acceleration_limits: false
    max_acceleration: 0
  joint_a3:
    has_velocity_limits: true
    max_velocity: 1.98967534727
    has_acceleration_limits: false
    max_acceleration: 0
  joint_a4:
    has_velocity_limits: true
    max_velocity: 3.31612557879
    has_acceleration_limits: false
    max_acceleration: 0
  joint_a5:
    has_velocity_limits: true
    max_velocity: 3.14159265359
    has_acceleration_limits: false
    max_acceleration: 0
  joint_a6:
    has_velocity_limits: true
    max_velocity: 4.53785605519
    has_acceleration_limits: false
    max_acceleration: 0
  left_inner_finger_joint:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  left_inner_knuckle_joint:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  right_inner_finger_joint:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  right_inner_knuckle_joint:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  right_outer_knuckle_joint:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0